/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ReservationManager {
        "apiBase": string;
    }
}
declare global {
    interface HTMLReservationManagerElement extends Components.ReservationManager, HTMLStencilElement {
    }
    var HTMLReservationManagerElement: {
        prototype: HTMLReservationManagerElement;
        new (): HTMLReservationManagerElement;
    };
    interface HTMLElementTagNameMap {
        "reservation-manager": HTMLReservationManagerElement;
    }
}
declare namespace LocalJSX {
    interface ReservationManager {
        "apiBase"?: string;
    }
    interface IntrinsicElements {
        "reservation-manager": ReservationManager;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "reservation-manager": LocalJSX.ReservationManager & JSXBase.HTMLAttributes<HTMLReservationManagerElement>;
        }
    }
}
